apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros-gazebo
  labels:
    app: ros-gazebo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros-gazebo
  template:
    metadata:
      labels:
        app: ros-gazebo
    spec:
      containers:
        - name: ros-gazebo
          image: ekhurtado/ros-tests:ros-gazebo
          imagePullPolicy: Always
          env:
#            - name: ROS_PACKAGE_PATH
#              value: /catkin_ws/src:/opt/ros/noetic/share
            - name: ROS_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ROS_MASTER_URI
              value: "http://$(ROS_IP):11311"
            - name: ROS_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      nodeSelector:
        kubernetes.io/hostname: worker1
      restartPolicy: Always
      serviceAccountName: ""

