apiVersion: v1
kind: PersistentVolume
metadata:
  name: ros-aas-core-archive
  labels:
    type: local
spec:
  storageClassName: ros-aas-core-archive
  capacity:
    storage: 800Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/ros_aas_core_archive"