FROM python:3.10-alpine

RUN pip install --upgrade pip

# aiokafka library requires installing these packages
RUN apk add --no-cache gcc gpgme-dev libc-dev

# All required Python packages are installed
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY src /

WORKDIR /src

ENV FLASK_APP=asset_integration.py

EXPOSE 7000

CMD flask run --host=0.0.0.0

# TODO De momento se han tenido problemas con ROS y contenedores, por lo que no se encapsulara el asset integration