FROM python:3.12
# This image of SMIA is built with the complete official Python image

RUN pip install --upgrade pip

# The required SMIA Python package is installed.
RUN pip install -i https://test.pypi.org/simple/ smia==0.2.1.8 --extra-index-url https://pypi.org/simple
#RUN pip install smia

WORKDIR /

#EXPOSE 5222

