FROM ekhurtado/smia:full-base-latest

CMD ["python3", "-m", "smia.launchers.smia_docker_starter"]
#CMD ["python3", "-m", "smia.launchers.smia_cli_starter", "--model", "/SMIA_TransportRobot_with_OWL.aasx"]

## Para mantener el contenedor arrancado:
#CMD [ "tail", "-f", "/dev/null"]
