apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: i4-0-smia-test
  namespace: kafka-ns
  labels:
    strimzi.io/cluster: mi-cluster-mensajeria
spec:
  partitions: 2
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
