FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

# Install Python 3.10
RUN apt update
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt update
RUN apt install -y python3.10

#RUN pip install --upgrade pip
#COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

# Install ROS: http://wiki.ros.org/noetic/Installation/Ubuntu
RUN apt-get update && apt-get upgrade -y
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-get install -y curl
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

ENV ROS_DISTRO=noetic
RUN apt update && apt-get install -y ros-noetic-ros-base \
    ros-noetic-actionlib-tools terminator python3-pip \
    && rm -rf /var/lib/apt/lists/*
#RUN apt-get update && apt-get install -y ros-noetic-moveit \
#    ros-noetic-ros-controllers \
#    ros-noetic-gazebo-ros-control \
#    ros-noetic-rosserial \
#    ros-noetic-roboticsgroup-upatras-gazebo-plugins \
#    ros-noetic-actionlib-tools terminator python3-pip

RUN apt-get update && apt-get install -y python3-rosdep
RUN rosdep init && rosdep update
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc


# Install specific packages
RUN apt-get install -y ros-noetic-slam-gmapping

#RUN source /opt/ros/noetic/setup.bash
RUN /bin/bash -c 'source /opt/ros/noetic/setup.bash'

# SET THE ENVIRONMENTAL VARIABLES RELATED TO ROS
#ENV ROS_MASTER_URI=http://192.168.1.5:11311
ENV ROS_MASTER_URI=http://192.168.1.61:11311
#ENV ROS_HOSTNAME=192.168.1.5
ENV ROS_HOSTNAME=192.168.1.61

COPY catkin_ws /
COPY src /

WORKDIR /

RUN apt-get update

#CMD ["rosrun", "turtlebot_main", "main.py"]
CMD ["python3", "-u", "main.py"]