FROM python:3.10-alpine

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install ROS: https://emanual.robotis.com/docs/en/platform/turtlebot3/quick-start/#pc-setup
RUN apt-get update && apt-get upgrade

COPY src /

WORKDIR /

CMD ["python3", "-u", "main.py"]