#https://answers.ros.org/question/303171/connection-between-ros-in-docker-with-external-ros-master-another-pc-the-baxter-case/
FROM ros:noetic-ros-base
# set enviroment

ENV ROS_MASTER_URI=http://192.168.233.130:11311
ENV ROS_MASTER_URI=http://localhost:11311
#ENV ROS_HOSTNAME=192.168.233.130
#ENV ROS_IP=192.168.233.130
#ENV ROS_WS=/home/catkin_ws
ENV ROS_DISTRO=noetic

RUN #mkdir -p $ROS_WS/src

COPY catkin_ws $ROS_WS
COPY src /

#WORKDIR $ROS_WS
WORKDIR /

# install ros dependencies packages

#RUN . "/opt/ros/$ROS_DISTRO/setup.sh" && cd $ROS_WS && catkin_make \
#    && sed --in-place --expression \
#     '$isource "$ROS_WS/devel/setup.bash"' \
#      /ros_entrypoint.sh
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN . "/opt/ros/$ROS_DISTRO/setup.sh"

# run ros package launch file
#CMD [ "roslaunch", "turtlebot_main", "main.py" ]
CMD [ "python3", "-u", "main.py"]

# Para mantener el contenedor arrancado:
#CMD [ "tail", "-f", "/dev/null"]
