FROM python:3.10-alpine

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Install ROS: http://wiki.ros.org/noetic/Installation/Ubuntu
RUN apt update && apt upgrade
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt install -y curl
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
RUN apt update
RUN apt install ros-noetic-desktop-full
RUN source /opt/ros/noetic/setup.bash

COPY catkin_ws /

WORKDIR /catkin_ws

CMD ["rosrun", "turtlebot_main", "main.py"]