FROM python:3.10-alpine

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY sender_agent.py /

WORKDIR /

EXPOSE 7000

CMD ["python3", "-u", "sender_agent.py"]