apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ros-aas-core-archive-claim
  name: ros-aas-core-archive-claim
spec:
  storageClassName: ros-aas-core-archive
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}