FROM ros:noetic-ros-base

RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc
RUN . "/opt/ros/$ROS_DISTRO/setup.sh"

RUN chmod +x /opt/ros/noetic/setup.bash
RUN /opt/ros/noetic/setup.bash

WORKDIR /catkin_ws

RUN mkdir -p /catkin_ws/src
RUN . "/opt/ros/$ROS_DISTRO/setup.sh" && catkin_make

COPY catkin_ws/src /catkin_ws/src/

COPY catkin_ws/src/turtlebot_main/maps /root/

RUN apt-get update && apt-get install -y \
    ros-noetic-tf \
    ros-noetic-turtlebot3-msgs \
    ros-noetic-gazebo-ros \
    ros-noetic-turtlebot3-bringup \
    ros-noetic-turtlebot3-navigation \
    ros-noetic-rviz 
#    ros-noetic-turtlebot3-simulations
#    ros-noetic-xacro \
#    ros-noetic-turtlebot3-description

RUN rosdep update

RUN . "/opt/ros/$ROS_DISTRO/setup.sh" && catkin_make

WORKDIR /catkin_ws/src/turtlebot_main

EXPOSE 11311

RUN echo "export ROS_PACKAGE_PATH=/catkin_ws/src:/opt/ros/noetic/share" >> ~/.bashrc
RUN export ROS_PACKAGE_PATH=/catkin_ws/src:/opt/ros/noetic/share

RUN export QT_X11_NO_MITSHM=1

# Para mantener el contenedor arrancado:
#CMD ["./scripts/initRViz.sh"]
CMD [ "tail", "-f", "/dev/null"]