FROM python:3.10-alpine

#RUN pip install Flask
#RUN pip install requests
#RUN pip install lxml

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src /

WORKDIR /

EXPOSE 7000

CMD ["python3", "-u", "aas_manager.py"]