FROM python:3.10-alpine

RUN pip install Flask

RUN pip install requests

RUN pip install lxml

COPY src/aas_manager.py /
COPY src/utilities /utilities

WORKDIR /

EXPOSE 7000

CMD ["python3", "-u", "aas_manager.py"]