FROM python:3.10-alpine

RUN pip install --upgrade pip

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY gui_agent.py /
COPY htmls /htmls
COPY gui_features /gui_features
COPY static /static

WORKDIR /

EXPOSE 10000

CMD ["python3", "-u", "gui_agent.py"]