apiVersion: v1
kind: PersistentVolume
metadata:
  name: x11-unix
  labels:
    type: local
spec:
  storageClassName: x11-unix
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/.X11-unix"